################################################################################
# This file is part of pyNFrac
# Copyright (C) 2016 Bert Vandenbroucke (bert.vandenbroucke@gmail.com)
#
# pyNFrac is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# pyNFrac is distributed in the hope that it will be useful,
# but WITOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with pyNFrac. If not, see <http://www.gnu.org/licenses/>.
################################################################################

##
# @file load_module.py
#
# @brief Load the Python module.
#
# The correct path to the module is generated by the CMake build system. Never
# edit this file directly, instead edit the version in the project test
# directory.
#
# @author Bert Vandenbroucke (bv7@st-andrews.ac.uk)
##

import sys

modulepath = "@PYTHON_MODULEPATH@"

sys.path.append(modulepath)

from pyNFrac import *
